#
# Makefile for Razer USB host to device mode switch
#

obj-$(CONFIG_RZR_DEVMODE)		+= usbdevice.o
obj-$(CONFIG_RZR_LED)			+= leddevice.o
obj-$(CONFIG_RZR_FILTER)		+= razerfilter.o
obj-$(CONFIG_RZR_HDMI_EDID)		+= hdmiedid.o
